name: NOX

on:
  push:
  pull_request:

jobs:
  nox:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Expo
        uses: actions/checkout@v2.4.0

      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Nox
        run: |
            pip install -U nox
            nox
